FROM python:3.9-alpine

RUN adduser -D rerunner

WORKDIR /home/rerunner

# It is just a single file with no dependencies except python core libaries
COPY src/tools/nightly_rerun.py .

RUN chown -R rerunner:rerunner ./

USER rerunner

CMD python tools/nightly_rerun.py
