version: '2.1'
services:
  webhook:
    restart: unless-stopped
    image: staticfloat/docker-webhook
    volumes:
      - ./:/code
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
      - WEBHOOK_HOOKS_DIR=/code/hooks
      - WEBHOOK_BRANCH_LIST=main
    ports:
      - 8000:8000
    networks:
      - backend
networks:
  backend:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
