FROM python:3.9-slim

RUN adduser --system extractor

WORKDIR /home/extractor

# needed for docker healthcheck
RUN apt-get update && apt-get install -y curl

# copy sources to image
COPY . /home/extractor

# install the package. this will use the pyproject.toml file to first build the wheel and then install it.
# using the generated artifact from the actual python build step would be nice, but piping the wheel file name
# via build-args through the docker/build-push-action@v3 turned out to be a massive problem.
RUN pip install --no-cache-dir /home/extractor/

USER extractor

# execute the entrypoint defined in pyproject.toml
CMD meta-lookup
