FROM femtopixel/google-chrome-headless AS FEMTOPIXEL

USER root

RUN rm -rf /var/lib/apt/lists/* && \
  apt-get update && \
  apt-get remove gnupg -y && apt-get install --reinstall gnupg2 dirmngr --allow-unauthenticated -y && \
  apt-get autoclean && \
  apt-get update && \
  apt-get install -y apt-transport-https ca-certificates curl gnupg --no-install-recommends && \
  curl -sSL https://deb.nodesource.com/setup_14.x | bash - && \
  apt-get install -y nodejs --no-install-recommends && \
  npm --global install npm && \
  npm --global install yarn && \
  apt-get purge --auto-remove -y curl gnupg && \
  rm -rf /var/lib/apt/lists/* && \
  npm install --global lighthouse && \
  mkdir -p /home/chrome/reports && chown -R chrome:chrome /home/chrome

RUN apt-get update || : && \
    apt-get install python3 -y && \
    apt-get install g++ python3-dev libxml2 libxml2-dev libffi-dev libssl-dev libxslt-dev -y && \
    apt-get install python3-pip -y

RUN apt-get install curl -y

# Needed for psycopg2
#RUN apt-get update && \
#    apt-get install build-deps gcc musl-dev && \
#    apt-get install postgresql-dev
# RUN dpkg -i ~/Downloads/libpq-dev_13.3-1.pgdg20.04+1_amd64.deb
RUN apt-get install libpq-dev -y
# RUN curl -o libpq.deb -fSL "http://apt.postgresql.org/pub/repos/apt/pool/main/p/postgresql-13/libpq-dev_13.3-1.pgdg20.04+1_amd64.deb"
# RUN apk add dpkg
# RUN dpkg -i libpq.deb

COPY requirements.txt requirements.txt
RUN pip3 install --no-cache-dir -r requirements.txt

USER chrome

ENV CHROME_FLAGS="--headless --disable-gpu --no-sandbox"

WORKDIR /home/chrome

COPY src/lighthouse/api.py .
COPY src/lib/constants.py lib/
COPY src/lib/settings.py lib/

CMD python3 api.py