version: '3.3'

services:
  extractor:
    dns: 8.8.8.8
    image: docker.edu-sharing.com/projects/oeh-redaktion/edusharing-projects-oeh-redaktion-metalookup-api:latest
    ports:
      - "5057:5057"
    links:
      - playwright
      - lighthouse
      - postgres
    depends_on:
      - postgres
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5057/_ping" ]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - traefik-public
    deploy:
      labels:
        - traefik.frontend.rule=Host:metalookup.openeduhub.net
        # 2.0
        #- "traefik.http.middlewares.testheader.headers.accesscontrolalloworigin=*"
        #- "traefik.http.middlewares.testheader.headers.addvaryheader=false"
        # 1.7
        #- "traefik.frontend.headers.customResponseHeaders=Access-Control-Allow-Origin:*||Access-Control-Allow-Methods:*"
        #- traefik.frontend.headers.customResponseHeaders=Access-Control-Allow-Methods:*
        - traefik.enable=true
        - traefik.port=5057
        - traefik.tags=traefik-public
        - traefik.docker.network=traefik-public
        - traefik.frontend.entryPoints=http,https
        - traefik.frontend.redirect.entryPoint=https

  playwright:
    dns: 8.8.8.8
    image: browserless/chrome
    restart: always
    environment:
      - "DEFAULT_LAUNCH_ARGS:[\"--disable-dev-shm-usage\"]"
      - "EXIT_ON_HEALTH_FAILURE=true"
    ports:
      - "3000:3000"
    networks:
      - traefik-public

  lighthouse:
    dns: 8.8.8.8
    image: docker.edu-sharing.com/projects/oeh-redaktion/edusharing-projects-oeh-redaktion-metalookup-lighthouse:latest
    restart: always
    ports:
      - "5058:5058"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5058/_ping" ]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - traefik-public

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - db_volume:/var/lib/postgresql/data
    networks:
      - traefik-public

volumes:
  db_volume:

networks:
  traefik-public:
    external: true
