name: Build images

on:
  pull_request:

jobs:
  build-and-push:
    name: Build Docker images
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build extractor
        run: docker build -t community.docker.edu-sharing.com/oeh-search-meta:latest .

      - name: Build lighthouse
        run: docker build -f dockerfile_lighthouse -t community.docker.edu-sharing.com/oeh-search-meta_lighthouse:latest .
