name: "Test, format, and build"

on: push

env:
  docker_repository: "docker.edu-sharing.com"
  path_prefix: "/projects/wlo/edu_sharing-projects-wlo-metalookup"

jobs:
  python-build-and-test:
    runs-on: ubuntu-latest
    env:
      PLAYWRIGHT_WS_ENDPOINT: ws://localhost:3000
      CACHE_DATABASE_URL: sqlite:///./cache.sqlite
    services:
      # Required for playwright unit tests
      playwright:
        image: browserless/chrome
        env:
          DEFAULT_LAUNCH_ARGS: '[\"--disable-dev-shm-usage\"]'
        ports:
          - "3000:3000"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # we need more than the last commit to figure out the version from the tags and commits.
          fetch-depth: 0

      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9.7"
          cache: 'poetry'
      - name: build artifact and install
        # always use the latest tag as package version. Not perfect, but anything else gets crazy with corner cases...
        run: |
          poetry env use 3.9
          poetry version $(git describe --tags --abbrev=0 | sed 's/^v//')
          poetry build
          poetry install
      - name: run pre-commit hooks
        run: poetry run pre-commit run --all-file
      - name: run pytest
        run: poetry run pytest
      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: wheel
          path: |
            dist/*.whl

  docker-build-and-push:
    strategy:
      matrix:
        include:
          - image: api
          - image: lighthouse
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            name=${{ env.docker_repository }}${{ env.path_prefix }}-${{ matrix.image }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern=v{{major}}.{{minor}}.{{patch}}

      - name: Login to EDU-Sharing Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.docker_repository }}
          username: ${{ secrets.DOCKER_EDU_HUB_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_EDU_HUB_REGISTRY_PASSWORD }}

      - name: Build and push Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: dockerfile_${{ matrix.image }}
          # only push if we build from main branch or a tag that matches
          push: ${{ github.ref == 'refs/heads/main' || github.ref_name == steps.version-tag-step.outputs.VERSION_TAG }}
          tags: ${{ steps.meta.outputs.tags }}
