name: Build and push Docker Images

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main

env:
  docker_repository: "docker.edu-sharing.com"
  path_prefix: "/projects/oeh-redaktion/edusharing-projects-oeh-redaktion-metalookup"

jobs:
  build-and-push-extractor:
    name: Build and Push Docker image to community edu hub
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Log in to edu sharing
        run: docker login ${{env.docker_repository}} -u ${{ secrets.DOCKER_EDU_HUB_REGISTRY_USERNAME }} -p ${{ secrets.DOCKER_EDU_HUB_REGISTRY_PASSWORD }}

      - name: Build the container
        run: docker build -t ${{env.docker_repository}}${{env.path_prefix}}-extractor:latest .

      - name: Push the Docker image
        run: docker push ${{env.docker_repository}}${{env.path_prefix}}-extractor:latest

  build-and-push-lighthouse:
    name: Build and Push Docker image to community edu hub
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Log in to edu sharing
        run: docker login ${{env.docker_repository}} -u ${{ secrets.DOCKER_EDU_HUB_REGISTRY_USERNAME }} -p ${{ secrets.DOCKER_EDU_HUB_REGISTRY_PASSWORD }}

      - name: Build the container
        run: docker build -f dockerfile_lighthouse -t ${{env.docker_repository}}${{env.path_prefix}}-lighthouse:latest .

      - name: Push the Docker image
        run: docker push ${{env.docker_repository}}${{env.path_prefix}}-lighthouse:latest

  build-and-push-nightly-rerun:
    name: Build and Push Docker image to community edu hub
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Log in to edu sharing
        run: docker login ${{env.docker_repository}} -u ${{ secrets.DOCKER_EDU_HUB_REGISTRY_USERNAME }} -p ${{ secrets.DOCKER_EDU_HUB_REGISTRY_PASSWORD }}

      - name: Build the container
        run: docker build -f dockerfile_nightly_rerun -t ${{env.docker_repository}}${{env.path_prefix}}-nightly_rerun:latest .

      - name: Push the Docker image
        run: docker push ${{env.docker_repository}}${{env.path_prefix}}-nightly_rerun:latest
